### PR TITLE
[Integrate-1744] Send notification(navigation) to jobs when create dataset / datamart / update-cache

### LINKED ISSUE #1744: Send feedback when adding new dataset
When add new dataset in dataset page, user can receive feedback after the prefect flow job finished, e.g 'Success/Failed to create new dataset'.

### PR DESCRIPTION
**Pull request by hengxian-jiang**
### Merge Checklist

Please cross check this list if additions / modifications needs to be done on top of your core changes and tick them off. Reviewer can as well glance through and help the developer if something is missed out.

- [ ] Automated Tests (Jasmine integration tests, Unit tests, and/or Performance tests)
- [ ] Updated Manual tests / Demo Config
- [ ] Documentation (Application guide, Admin guide, Markdown, Readme and/or Wiki)
- [ ] Verified that local development environment is working with latest changes (integrated with latest `develop` branch)
- [ ] following best practices in [code review doc](../code_review.md)

Screenshot 2026-04-01 at 9 46 36 AM
Screenshot 2026-04-01 at 9 50 51 AM
Screenshot 2026-04-01 at 9 52 32 AM

### CODE REVIEW

**Review by suwarnoong — APPROVED** [review]

File: ui/apps/portal/src/contexts/app-context/states/translation-state.ts [hunk 1]
```diff
@@ -269,6 +271,8 @@ export const i18nDefault = {
     COPY_STUDY_DIALOG__NO_TABLE_CHOSEN: "Table Filter is checked, but no table was chosen!",
     COPY_STUDY_DIALOG__PA_CONFIG_REQUIRED: "PA config ID is required!",
     COPY_STUDY_DIALOG__TABLE_FILTER: "Table filter",
+    COPY_STUDY_DIALOG__DATAMART_CREATED_TITLE: "Datamart Created",
```
Comment (suwarnoong) [inline ui/apps/portal/src/contexts/app-context/states/translation-state.ts]: Should this be sentence case?

File: ui/apps/portal/public/translations/de.json [hunk 2]
```diff
@@ -545,6 +551,9 @@
   "EDIT_TENANT_ROLE_DIALOG__SAVE": "Speichern",
   "EXECUTE_FLOW_DIALOG__ERROR_DESCRIPTION": "Bitte versuchen Sie es erneut. Um den Fehler zu melden, senden Sie eine E-Mail an help@data4life.care.",
   "FEATURE__ADMIN_ONLY_SHARING": "Nur Admin-Freigabe",
+  "FLOW_RUN_NOTIFICATION_DIALOG__CLOSE": "Schließen",
+  "FLOW_RUN_NOTIFICATION_DIALOG__VIEW_FLOW_RUN": "Flow-Lauf anzeigen",
+  "FLOW_RUN_NOTIFICATION_DIALOG__PROGRESS_MESSAGE": "Den Fortschritt können Sie auf der Seite „Jobs" verfolgen.",
```
Comment (suwarnoong) [inline ui/apps/portal/public/translations/de.json]: It seems like some invalid json here

Comment (hengxian-jiang) [reply ui/apps/portal/public/translations/de.json]: checking

File: ui/apps/portal/src/contexts/app-context/states/translation-state.ts (hunk 1 above)
Comment (hengxian-jiang) [reply ui/apps/portal/src/contexts/app-context/states/translation-state.ts]: Good catch, will resolve the issue
