### PR TITLE
Jerome ng/2024 column header tooltips and sorting

### LINKED ISSUE #2022: `conceptRecordCount` endpoint returns 500 when search yields no matching concepts
### Description

When a user searches for a term that has no matching concepts in the dataset vocabulary (e.g., "hypertension" in the demo dataset which only has 444 concepts), the `POST /d2e/d2e-webapi/cdmresults/{datasetId}/conceptRecordCount` endpoint returns HTTP 500 instead of an empty result.

The root cause is that the frontend sends an empty array `[]` of concept IDs, and the backend generates invalid SQL: `WHERE concept_id IN ()`.

### Steps to Reproduce

1. Navigate to the Concepts page (`/d2e/portal/researcher/concepts`)
2. In the Concept Search tab, type **"hypertension"** and press Enter
3. Open browser DevTools → Network tab
4. Observe the `conceptRecordCount` POST request returns **500 Internal Server Error**

For comparison, searching **"diabetes"** (which has 1 matching concept in the demo dataset) works correctly — `conceptRecordCount` returns 200.

### Expected Behavior

When the vocabulary search returns 0 matching concepts, the `conceptRecordCount` call should either:
- Not be called (frontend guard), or
- Return HTTP 200 with an empty array (backend guard)

### Actual Behavior

- `conceptRecordCount` returns `{"statusCode": 500, "error": "Internal Server Error", "message": ""}`
- The UI shows "No records to display" (which is correct), but the console logs a 500 error

### Root Cause

**Call chain:**

1. `TerminologyList.tsx:282` — After search, calls `getConceptRecordCounts()` with `concepts.map((e) => e.CONCEPT_ID)`. When the search returns 0 concepts, this passes an **empty array `[]`**.

2. `cdmresults.service.ts:16` — Passes the empty array to `trexDao.getConceptRecordCount(conceptIds, dcResultsSchemaName)` with no empty check.

3. `trex.dao.ts:290-293` — Builds SQL with:
   ```sql
   WHERE concept_id IN (${conceptIds.join(", ")})
   ```
   When `conceptIds` is `[]`, `.join(", ")` produces `""`, resulting in:
   ```sql
   WHERE concept_id IN ()
   ```
   This is **invalid SQL** and throws an unhandled exception.

### Suggested Fix

Guard against empty arrays. Either:

**Option A — Frontend guard** (in `TerminologyList.tsx`):
```typescript
// Skip the API call if there are no concepts
if (concepts.length > 0) {
  const conceptRecordCounts = await api.d2eWebapi.getConceptRecordCounts(
    datasetId,
    concepts.map((e) => e.CONCEPT_ID),
    controller.signal,
  );
  mappedConcepts = combinedConceptAndConceptRecordCounts(
    concepts.map(mapd2eWebapiConcept),
    conceptRecordCounts,
  );
} else {
  mappedConcepts = [];
}
```

**Option B — Backend guard** (in `trex.dao.ts`):
```typescript
async getConceptRecordCount(conceptIds: number[], dcResultsSchemaName: string) {
  if (dcResultsSchemaName === "" || conceptIds.length === 0) {
    return [];
  }
  // ... existing SQL query
}
```

Option B is more defensive (protects against other callers sending empty arrays). Both could be applied.

### Additional Note

The SQL in `trex.dao.ts:293` uses string interpolation for concept IDs (`${conceptIds.join(", ")}`) rather than parameterized queries. While the input is Zod-validated as `z.array(z.number())` at the route level, parameterized queries would be a safer pattern.

### Environment

- Branch: `develop`
- Dataset: Demo dataset (444 concepts)
- Verified via DuckDB query: `SELECT * FROM demo_cdm.concept WHERE LOWER(concept_name) LIKE '%hypertension%'` returns 0 rows

### LINKED ISSUE #2024: Concept Search table: RC, DRC, PC, DPC column headers have no tooltips explaining abbreviations
### Description

The Concept Search table uses abbreviated column headers — RC, DRC, PC, DPC — for the record count metrics. These abbreviations have no tooltips or other explanation in the UI. While experienced OMOP users may recognize them, new users or those unfamiliar with OMOP CDM will not understand what these columns represent.

Other columns (ID, Code, Name, Vocabulary, Concept, Domain, Class, Validity) use full words and are self-explanatory.

### Steps to Reproduce

1. Navigate to the Concepts page (`/d2e/portal/researcher/concepts`)
2. Observe the table headers — the rightmost 4 columns show: **RC**, **DRC**, **PC**, **DPC**
3. Hover over any of these headers — no tooltip appears

### Expected Behavior

Hovering over the abbreviated column headers should show a tooltip with the full name:

| Header | Tooltip |
|--------|---------|
| **RC** | Record Count |
| **DRC** | Descendant Record Count |
| **PC** | Person Count |
| **DPC** | Descendant Person Count |

### Code Reference

**Column headers** are defined via i18n keys in:

`ui/apps/concept-sets/src/context/state/translation-state.ts` (lines 87-90):
```typescript
TERMINOLOGY_LIST__RECORD_COUNT: "RC",
TERMINOLOGY_LIST__DESCENDANT_RECORD_COUNT: "DRC",
TERMINOLOGY_LIST__PERSON_COUNT: "PC",
TERMINOLOGY_LIST__DESCENDANT_PERSON_COUNT: "DPC",
```

**Column definitions** are in `ui/apps/concept-sets/src/Terminology/components/TerminologyList/TerminologyList.tsx` (lines 671-714). The columns use MaterialReactTable's `header` property but have no `muiTableHeadCellProps.title` or `Header` render override to add tooltips.

### Suggested Fix

Add `muiTableHeadCellProps` with a `title` attribute to each column definition. For example:

```typescript
{
  accessorKey: "recordCount",
  header: getText(i18nKeys.TERMINOLOGY_LIST__RECORD_COUNT),
  muiTableHeadCellProps: {
    title: "Record Count",
  },
  grow: true,
  size: 50,
},
```

Alternatively, the i18n values could be changed to full names (e.g., `"Record Count"` instead of `"RC"`), but this may cause column width issues given the table already has 12+ columns at 1920px.

### Environment

- Branch: `develop`
- Component: `ui/apps/concept-sets/src/Terminology/components/TerminologyList/TerminologyList.tsx`

Image

### PR DESCRIPTION
**Pull request by jerome-ng**
- Added sorting for concepts. 
- The counts come from separate tables so sorting for counts are done in code instead of in the db. 
- sorting is ASC for non counts and DESC for counts as users will like want to see the large counts. 
- Some adjustments to column widths were done too. 
- Tooltops on hover for counts are shown now.
- Image below shows 'RC' sorted

Screenshot 2026-04-02 at 1 13 43 PM
Screenshot 2026-04-02 at 1 17 22 PM

## Summary

  - Adds server-side sorting for all columns in the Concept Search table (ID, Name, Code, Vocabulary, Domain, Class, Validity, Score, RC, DRC, PC, DPC)
  - Standard columns sort via SQL `ORDER BY` in terminology-svc
  - Count columns (RC/DRC/PC/DPC) sort via a two-step path: fetch all matching concept IDs → batch-fetch achilles counts → sort in Node → return page

  Standard column sort (e.g. Name):

    Browser → d2e-webapi → terminology-svc
                                │
                           ORDER BY concept_name ASC
                           LIMIT 25 OFFSET 0
                                │
                           ◄── page of concepts
                                │
    Browser ◄── concepts ◄── d2e-webapi
    Browser → d2e-webapi → conceptRecordCount (25 IDs)
    Browser ◄── counts

  Count column sort (e.g. Record Count):

    Browser → d2e-webapi → terminology-svc GET /concept/ids
                                │
                           SELECT concept_id FROM fts
                           (all matching IDs, no LIMIT)
                                │
                           ◄── [id, id, id, ...]
                                │
                           d2e-webapi batches IDs (1k per batch)
                                │
                           ┌─── batch 1 ──► achilles_result_concept_count
                           ├─── batch 2 ──► achilles_result_concept_count
                           └─── batch N ──► (5 concurrent, 3 retries each)
                                │
                           sort by count in Node
                           slice to page (25 IDs)
                                │
                           d2e-webapi → getConceptsFromIdentifiers (25 IDs)
                                │
    Browser ◄── concepts ◄── d2e-webapi
    Browser → d2e-webapi → conceptRecordCount (25 IDs)
    Browser ◄── counts

  ## Changes

  **terminology-svc**
  - `conceptSchemas.ts`: Added `sortBy` (enum whitelist), `sortOrder` params; new `getConceptIdsQuery` schema
  - `concept.ts`: New `getConceptIds` controller
  - `cachedb-dao.ts` / `hana-hdb-dao.ts`: `buildOrderByClause()` with column whitelist; new `getConceptIds()` method
  - `cachedb.ts`: Routes `sortBy`/`sortOrder` to DAO; new `getConceptIds()` pass-through
  - `routes.ts` / `conceptApi.ts`: Registered `GET /concept/ids` endpoint

  **d2e-webapi**
  - `vocabulary.service.ts`: Two-step count-sort path (fetch IDs → batch achilles counts → sort → fetch page details)
  - `helpers/count-sort.ts`: Extracted batching, retry, and concurrency utilities
  - `TerminologySvcAPI.ts`: New `getConceptIds()` method
  - `routes/vocabulary.ts`: Added `sortBy`/`sortOrder` to search route
  - `trex.dao.ts`: Empty array guard on `getConceptRecordCount`
  - `package.json`: Added gateway scope for `/concept/ids`

  **concept-sets UI**
  - `TerminologyList.tsx`: Sort state wired to API params; `sortDescFirst: true` on count columns only; column size adjustments
  - `d2e-webapi.ts`: Passes `sortBy`/`sortOrder` query params

### CODE REVIEW

File: functions/d2e-webapi/src/api/TerminologySvcAPI.ts [hunk 1]
```diff
@@ -195,6 +197,12 @@ export class TerminologySvcAPI {
       if (filters) {
         url.searchParams.set("filter", JSON.stringify(filters));
       }
+      if (sortBy) {
```
Comment (jerome-ng) [inline functions/d2e-webapi/src/api/TerminologySvcAPI.ts:200]: Passing new sorting params to terminology api call

File: functions/d2e-webapi/src/api/TerminologySvcAPI.ts [hunk 2]
```diff
@@ -203,6 +211,27 @@ export class TerminologySvcAPI {
     }
   }
 
+  async getConceptIds(
```
Comment (jerome-ng) [inline functions/d2e-webapi/src/api/TerminologySvcAPI.ts:214]: New for getting only IDs for a search query

File: functions/d2e-webapi/src/dao/trex.dao.ts [hunk 3]
```diff
@@ -282,11 +282,25 @@ export class TrexDAO {
     conceptIds: number[],
     dcResultsSchemaName: string
   ): Promise<IConceptRecordCount[]> {
+    if (conceptIds.length === 0) {
```
Comment (jerome-ng) [inline functions/d2e-webapi/src/dao/trex.dao.ts:285]: Addresses https://github.com/OHDSI/Data2Evidence/issues/2022

File: functions/d2e-webapi/src/helpers/count-sort.ts [hunk 4]
```diff
@@ -0,0 +1,54 @@
+export const COUNT_SORT_COLUMNS = new Set([
```
Comment (jerome-ng) [inline functions/d2e-webapi/src/helpers/count-sort.ts:1]: This is for doing the sorting of record counts. there is parallelism and retry mechanism so make it less unlikely for large concept counts to fail

File: functions/d2e-webapi/src/routes/vocabulary.ts [hunk 5]
```diff
@@ -361,6 +361,8 @@ export const vocabulary: FastifyPluginAsyncZod = async function (app) {
         querystring: z.object({
           page: z.coerce.number(),
           rowsPerPage: z.coerce.number(),
+          sortBy: z.string().optional(),
```
Comment (jerome-ng) [inline functions/d2e-webapi/src/routes/vocabulary.ts:364]: input validation for new params

File: functions/d2e-webapi/src/services/vocabulary.service.ts [hunk 6]
```diff
@@ -233,14 +244,84 @@ export const searchConcept = async (
...
+          PERSON_COUNT: Number(row.PERSON_COUNT),
+          DESCENDANT_PERSON_COUNT: Number(row.DESCENDANT_PERSON_COUNT),
+        });
+      }
+    }
+
+    // Sort by the requested count column
+    const sortField = COUNT_COLUMN_FIELD_MAP[sortBy!];
+    const isDesc = !sortOrder || sortOrder === "desc";
+    const sorted = allIds
```
Comment (jerome-ng) [inline functions/d2e-webapi/src/services/vocabulary.service.ts:278]: All the unsorted conceptId-counts are sorted, then paginated

File: ui/apps/concept-sets/src/Terminology/components/TerminologyList/TerminologyList.tsx [hunk 7]
```diff
@@ -673,8 +714,12 @@ const TerminologyList: FC<TerminologyListProps> = ({
               {
                 accessorKey: "recordCount",
                 header: getText(i18nKeys.TERMINOLOGY_LIST__RECORD_COUNT),
+                muiTableHeadCellProps: {
```
Comment (jerome-ng) [inline ui/apps/concept-sets/src/Terminology/components/TerminologyList/TerminologyList.tsx:717]: Tool tips and widths changed here

**Review by maggie-li-yd — APPROVED** [review]

**Review by suwarnoong — APPROVED** [review]
