### PR TITLE
[Integrate-2241] Fix edit and delete metadata attribute notification

### LINKED ISSUE #2241: Metadata - Incorrect notification when editing attribute
**Step:**
1. On Metadata page, Add new Attribute successfully
2. Edit the newly created attribute and observe the notification.

**Expected Result:**
Notification should be displayed **"Attribute config edited successfully"**

**Actual Result:**
**"Attribute config added successfully."** is displayed when editing a record.

Image

### LINKED ISSUE #2243: Metadata - Missing notification when deleting attribute
**Step:**
1. On Metadata page, Add new Attribute successfully
2. Deleting attribute and observe the notification

**Expected Result:**
Notification should appear after deleting Attribute

**Actual Result:**
Missing notification when deleting a record

https://github.com/user-attachments/assets/72b3921b-22ce-4d04-a8d5-fd0242d0b026

### PR DESCRIPTION
**Pull request by hengxian-jiang**
### Merge Checklist

Please cross check this list if additions / modifications needs to be done on top of your core changes and tick them off. Reviewer can as well glance through and help the developer if something is missed out.

- [ ] Automated Tests (Jasmine integration tests, Unit tests, and/or Performance tests)
- [ ] Updated Manual tests / Demo Config
- [ ] Documentation (Application guide, Admin guide, Markdown, Readme and/or Wiki)
- [ ] Verified that local development environment is working with latest changes (integrated with latest `develop` branch)
- [ ] following best practices in [code review doc](../code_review.md)

### CODE REVIEW

File: ui/apps/portal/src/contexts/app-context/states/translation-state.ts [hunk 1]
```diff
@@ -895,6 +895,7 @@ export const i18nDefault = {
     SAVE_ATTRIBUTE_DIALOG__EDIT: "Edit attribute",
     SAVE_ATTRIBUTE_DIALOG__SAVE: "Save",
     SAVE_ATTRIBUTE_DIALOG__SUCCESS: "Attribute config added successfully.",
+    SAVE_ATTRIBUTE_DIALOG__EDIT_SUCCESS: "Attribute config edited successfully.",
```
Comment (suwarnoong) [inline ui/apps/portal/src/contexts/app-context/states/translation-state.ts:898]: Could you also add the translation for zh and de?

**Review by KangJingA — APPROVED** [review]
