### PR TITLE
Fix concepts not showing

### LINKED ISSUE #647: [Concept Set] Concepts not rendering when navigated from PA
To replicate error, click on `+` button in PA
Image

Concepts are not render although network request is successful
Image

### PR DESCRIPTION
**Pull request by jerome-ng**
Fixes issue where concepts were received via api, but not showing the in the terminology UI.

This issue is unusual as it only occurs when portal is built, but not in react dev server.

The causing code change was meant to set default filters immediately when available. The fix reverts this change, which means there will be a quick visible ui update seen when default filters are used where it goes from empty to filled.

### Merge Checklist

Please cross check this list if additions / modifications needs to be done on top of your core changes and tick them off. Reviewer can as well glance through and help the developer if something is missed out.

- [ ] Automated Tests (Jasmine integration tests, Unit tests, and/or Performance tests)
- [ ] Updated Manual tests / Demo Config
- [ ] Documentation (Application guide, Admin guide, Markdown, Readme and/or Wiki)
- [ ] Verified that local development environment is working with latest changes (integrated with latest `develop` branch)
- [ ] following best practices in [code review doc](../code_review.md)

### CODE REVIEW

File: ui/apps/portal/src/plugins/Researcher/Terminology/components/TerminologyList/TerminologyList.tsx [hunk 1]
```diff
@@ -217,6 +209,31 @@ const TerminologyList: FC<TerminologyListProps> = ({
     [onSelectConceptId]
   );
 
+  useEffect(() => {
+    if (columnFilters.length || !defaultFilters) {
+      setUseDefaultFilters(false);
+    }
+  }, [columnFilters.length, defaultFilters]);
+
+  useEffect(() => {
```
Comment (jerome-ng) [inline ui/apps/portal/src/plugins/Researcher/Terminology/components/TerminologyList/TerminologyList.tsx:218]: These code were present in the past. reverting

**Review by brandantck — APPROVED** [review]

**Review by p-hoffmann — APPROVED** [review]

**Review by SantanM — APPROVED** [review]
