### PR TITLE
Fix numeric barchart. Improve typing

### LINKED ISSUE #1371: [BUG] Cohort - The bar chart shows blank when 'Race Concept ID' is selected
Cohorts -  In the attribute selection box x1 / x2  for the x-axis label at the lower-left graph corner, choose Basic Data > “Race concept id”. The bar chart is not shown. 

https://github.com/user-attachments/assets/04b4f3a6-6ddb-4656-a404-2021a465bd30

- This issue also occurs with Attribute Age , Year of birth, Gender concept id , Month of Birth...

### PR DESCRIPTION
**Pull request by jerome-ng**
`patient.attribute.Age` is number `39`. `patient.attribute.raceconceptid` is string `"0"`. Barchart works for raceconceptid but was blank for age. Code was failing where a string method was being used on the number.

Screenshot 2025-12-11 at 1 28 41 PM
Screenshot 2025-12-11 at 1 29 11 PM

X1 with age works now:
Screenshot 2025-12-11 at 1 34 44 PM

### CODE REVIEW

File: ui/apps/vue-mri-ui-lib/src/store/modules/chartUtils.ts [hunk 1]
```diff
@@ -76,7 +78,9 @@ const getters = {
         // Custom tooltip labelling
         let hoverTemplate = ''
         if (xAxes.length === 1) {
-          xData = category.data.map(data => truncateAtWordBoundary(data[xAxes[0].id], Constants.XAxisLabelMaxLength))
+          xData = category.data.map(data =>
+            truncateAtWordBoundary(String(data[xAxes[0].id]), Constants.XAxisLabelMaxLength)
```
Comment (jerome-ng) [inline ui/apps/vue-mri-ui-lib/src/store/modules/chartUtils.ts:82]: Fix is `String` here

File: ui/apps/vue-mri-ui-lib/src/store/modules/chartUtils.ts [hunk 2]
```diff
@@ -86,7 +90,7 @@ const getters = {
         } else {
           // Truncate labels for x-axis display
           xData = xAxes.map(xAxis =>
-            category.data.map(data => truncateAtWordBoundary(data[xAxis.id], Constants.XAxisLabelMaxLength))
+            category.data.map(data => truncateAtWordBoundary(String(data[xAxis.id]), Constants.XAxisLabelMaxLength))
```
Comment (jerome-ng) [inline ui/apps/vue-mri-ui-lib/src/store/modules/chartUtils.ts:93]: and here

**Review by maggie-li-yd — APPROVED** [review]
