### PR TITLE
[Analyze-994] Fix save rename on enter for pa cohort

### LINKED ISSUE #994: Cohort - The ENTER key does not work for Rename Saved Filter dialog
The ENTER key does not work for Rename Saved Filter dialog

Image

### PR DESCRIPTION
**Pull request by maggie-li-yd**
Fix cohort renaming on enter key down for PA.

### Merge Checklist

Please cross check this list if additions / modifications needs to be done on top of your core changes and tick them off. Reviewer can as well glance through and help the developer if something is missed out.

- [ ] Automated Tests (Jasmine integration tests, Unit tests, and/or Performance tests)
- [ ] Updated Manual tests / Demo Config
- [ ] Documentation (Application guide, Admin guide, Markdown, Readme and/or Wiki)
- [ ] Verified that local development environment is working with latest changes (integrated with latest `develop` branch)
- [ ] following best practices in [code review doc](../code_review.md)

### CODE REVIEW

File: ui/apps/vue-mri-ui-lib/src/components/Bookmarks.vue [hunk 1]
```diff
@@ -392,6 +392,7 @@ export default {
       }
     },
     confirmRenameBookmark() {
+      if (this.hasExceededLength) return
```
[the remark this answers is not in the document]
Comment (maggie-li-yd) [reply ui/apps/vue-mri-ui-lib/src/components/Bookmarks.vue:395]: maxlength is set at 40 for rename input.

Comment (jerome-ng) [inline ui/apps/vue-mri-ui-lib/src/components/Bookmarks.vue:395]: what is the purpose of moving it from on top to below? seems to have same behaviour

Comment (maggie-li-yd) [reply ui/apps/vue-mri-ui-lib/src/components/Bookmarks.vue:395]: Vue 3's inline handler detection doesn't reliably execute complex expressions with `&&` as event handlers. The `confirmRenameBookmark` function ends up not being called in `@keydown.enter="!hasExceededLength && confirmRenameBookmark"` even when `!hasExceededLength` evaluates to true. This causes the submit cohort renaming on enter keydown to not work and hence the proposed changes.

**Review by jerome-ng — APPROVED** [review]
