### PR TITLE
Setup e2e for easy local runs, fix some related bugs in code and tests

### LINKED ISSUE #1673: Improve e2e local setup

### PR DESCRIPTION
**Pull request by jerome-ng**
- Use docker to run playwright tests locally and in github actions
- remove pixel diff requirement except in filtering-barcharts which seems to have a ui bug. issue created
- add a cli to do the tests locally
- tests use separate name space, but running containers should be removed due to high resource usage

```
╰─ ./scripts/e2e.sh

╔════════════════════════════════════════╗
║      E2E Testing Wizard                ║
╚════════════════════════════════════════╝

  Branch: jerome-ng-local-e2e-setup
  Available sessions: 1

  Actions
  1) Fresh Setup & Test       - Build, start, and run tests
  2) Fresh Setup Only         - Build and start without running tests
  3) Restore & Retest         - Reset to snapshot and run tests
  4) Restore Only             - Reset to snapshot without running tests

  Session Management
  5) List sessions
  6) Remove session           - Stop and delete all volumes

  q) Quit

  Enter choice: 1

  Build and mount UI? [Y/n]: y
  Branch to checkout [current]:
  Test filter (e.g., filtering-bar) [all]:
  Update screenshots (regenerate baselines)? [y/N]:

  Configuration
  ─────────────────────────────────
  Action:             Fresh Setup & Test
  Build/mount UI:     yes
  Plugins update:     no (keep installed)
  Test filter:        all tests
  Update screenshots: no
```

### Merge Checklist

Please cross check this list if additions / modifications needs to be done on top of your core changes and tick them off. Reviewer can as well glance through and help the developer if something is missed out.

- [ ] Automated Tests (Jasmine integration tests, Unit tests, and/or Performance tests)
- [ ] Updated Manual tests / Demo Config
- [ ] Documentation (Application guide, Admin guide, Markdown, Readme and/or Wiki)
- [ ] Verified that local development environment is working with latest changes (integrated with latest `develop` branch)
- [ ] following best practices in [code review doc](../code_review.md)

### CODE REVIEW

File: ui/apps/jobs/src/utils/api.ts [hunk 1]
```diff
@@ -1,10 +1,49 @@
...
+}
+
+type AxiosInstanceSetupHook = NonNullable<Parameters<typeof createApi>[1]>
+
+/**
+ * Setup hook to add retry logic for ERR_NETWORK_CHANGED errors.
+ * This error occurs when Docker containers start up and cause network
+ * interface changes, which can interrupt in-flight HTTP requests.
+ */
+const setupNetworkErrorHandler: AxiosInstanceSetupHook = (instance) => {
```
Comment (jerome-ng) [inline ui/apps/jobs/src/utils/api.ts:15]: https://issues.chromium.org/issues/41465264

There is an issue with chromium based browsers (firefox handles this differently) when the docker network refreshes when containers start/stop. As we are running playwright inside a docker container, when such events happen, the network has changes and the chromium will have errors. Tests related to this are mostly in the flows tests as it spins up new flow containers, although it can happen elsewhere potentially too. This issue should not affect normal browser usage.

File: ui/Dockerfile.build [hunk 2]
```diff
@@ -0,0 +1,20 @@
+# Dockerfile for building UI in a consistent bun environment
```
Comment (jerome-ng) [inline ui/Dockerfile.build:1]: Added a way to build the ui files inside docker, to make builds more reproducible. Only used for e2e tests for now

File: ui/apps/portal/src/plugins/mri/PatientAnalytics/Atlas.tsx [hunk 3]
```diff
@@ -10,6 +10,20 @@ type Props = {
 export const Atlas: FC<Props> = ({ datasetId, getToken, username, toggleAtlas, atlasPath }) => {
   const iframeRef = React.useRef<HTMLIFrameElement>(null);
   const [tokenInterval, setTokenInterval] = useState<NodeJS.Timer | null>(null);
+  const [tokenReady, setTokenReady] = useState(false);
```
Comment (jerome-ng) [inline ui/apps/portal/src/plugins/mri/PatientAnalytics/Atlas.tsx:13]: Fixes a race condition in the loading of atlas lite, where the datasetId is not available initially if d2e-atlas loads too quickly. since atlas-lite is housed in the same place, we just directly use sessionStorage to initialise it

File: tests/e2e/tests/02-users/add-delete-user.spec.ts [hunk 4]
```diff
@@ -30,15 +30,15 @@ test(TEST_NAME, async ({ page }) => {
...
-  await page.waitForTimeout(10000)
+  await page.waitForTimeout(1000)
   await page.reload()
   await expect(page.getByRole('cell', { name: 'test_user' })).toBeVisible()
 
   // Delete user
   await page.getByRole('button', { name: 'Delete' }).nth(1).click()
   await page.getByRole('button', { name: 'Yes, delete' }).click()
   // Check if user is deleted
+  await page.waitForTimeout(500)
```
Comment (jerome-ng) [inline tests/e2e/tests/02-users/add-delete-user.spec.ts:41]: Wait for delete to complete then reload, or user might still be there on the first reload

File: tests/e2e/tests/05-datasets/add-dataset-with-existing-schema.spec.ts [hunk 5]
```diff
@@ -72,44 +74,44 @@ test(TEST_NAME, async ({ page }) => {
   await page.getByRole('option', { name: 'omop5-4 [omop_cdm_plugin]' }).click()
   await page.locator('#mui-component-select-paConfigOption').click()
   await page.getByRole('option', { name: 'OMOP', exact: true }).click()
-  await page.getByRole('textbox', { name: 'Token dataset code' }).fill('new_test_dataset')
+  await page.getByRole('textbox', { name: 'Token dataset code' }).fill(`${randomString}1`)
```
Comment (jerome-ng) [inline tests/e2e/tests/05-datasets/add-dataset-with-existing-schema.spec.ts:77]: using random string for the test so retries will be valid to run as well

File: tests/e2e/tests/05-datasets/add-dataset-with-existing-schema.spec.ts [hunk 6]
```diff
@@ -124,35 +126,35 @@ test(TEST_NAME, async ({ page }) => {
   await page.getByRole('checkbox', { name: /use default result schema name/i }).uncheck()
   await page.getByRole('textbox', { name: 'Result Schema Name' }).fill(`result_schema_${randomString}`)
   await page.locator('#mui-component-select-dataModelOption').click()
-  await expect(page.getByRole('option', { name: 'omop5-3 [omop_cdm_plugin]' })).toBeVisible({ timeout: 1000 })
+  await expect(page.getByRole('option', { name: 'omop5-3 [omop_cdm_plugin]' })).toBeVisible()
   await page.getByRole('option', { name: 'omop5-3 [omop_cdm_plugin]' }).click()
   await page.locator('#mui-component-select-paConfigOption').click()
   await page.getByRole('option', { name: 'OMOP', exact: true }).click()
-  await page.getByRole('textbox', { name: 'Token dataset code' }).fill('new_test_dataset_2')
+  await page.getByRole('textbox', { name: 'Token dataset code' }).fill(`${randomString}2`)
```
Comment (jerome-ng) [inline tests/e2e/tests/05-datasets/add-dataset-with-existing-schema.spec.ts:133]: using random string for the test so retries will be valid to run as well

File: tests/e2e/tests/05-datasets/new-schema-data-management-plugin-mi.spec.ts [hunk 7]
```diff
@@ -1,72 +1,76 @@
...
+  await page.getByRole('option', { name: 'demo_database-postgres' }).click()
+  // Uncheck the "Use default result schema name" checkbox to enable custom input
+  await page.getByRole('checkbox', { name: /use default result schema name/i }).uncheck()
+  await page.getByRole('textbox', { name: 'Result Schema Name' }).fill(`result_schema_${randomString}`)
+  await page.locator('#mui-component-select-dataModelOption').click()
+  await page.getByRole('option', { name: 'medical-imaging [data_management_plugin]' }).click()
+  await page.locator('#mui-component-select-paConfigOption').click()
+  await page.getByRole('option', { name: 'OMOP', exact: true }).click()
+  await page.getByRole('textbox', { name: 'Token dataset code' }).click()
+  await page.getByRole('textbox', { name: 'Token dataset code' }).fill(randomString)
```
Comment (jerome-ng) [inline tests/e2e/tests/05-datasets/new-schema-data-management-plugin-mi.spec.ts:39]: using random string for the test so retries will be valid to run as well. the rest are semi colons

File: tests/e2e/tests/05-datasets/new-schema-data-management-plugin-omop.spec.ts [hunk 8]
```diff
@@ -1,69 +1,75 @@
...
+  await page.getByRole('option', { name: 'demo_database-postgres' }).click()
+  // Uncheck the "Use default result schema name" checkbox to enable custom input
+  await page.getByRole('checkbox', { name: /use default result schema name/i }).uncheck()
+  await page.getByRole('textbox', { name: 'Result Schema Name' }).fill(`result_schema_${randomString}`)
+  await page.locator('#mui-component-select-dataModelOption').click()
+  await page.getByRole('option', { name: 'omop5-4 [data_management_plugin]' }).click()
+  await page.locator('#mui-component-select-paConfigOption').click()
+  await page.getByRole('option', { name: 'OMOP', exact: true }).click()
+  await page.getByRole('textbox', { name: 'Token dataset code' }).click()
+  await page.getByRole('textbox', { name: 'Token dataset code' }).fill(randomString)
```
Comment (jerome-ng) [inline tests/e2e/tests/05-datasets/new-schema-data-management-plugin-omop.spec.ts:38]: using random string for the test so retries will be valid to run as well. rest are semicolons

File: tests/e2e/tests/05-datasets/new-schema-i2b2-plugin.spec.ts [hunk 9]
```diff
@@ -1,71 +1,75 @@
...
   // Get the first (top) entry link
-  const firstEntry = page.locator('a:has(span:text("datamodel-create-cdm_tsi2b2_"))').first()
-  // Find the closest state badge to this entry (adjust the selector as needed)
-  const stateBadge = firstEntry.locator(
-    'xpath=ancestor::div[contains(@class,"state-list-item__content")]//span[contains(@class,"state-badge")]'
-  )
-  await expect(stateBadge).toHaveText(/Completed/, { timeout: 120000 })
+  const firstEntry = page
+    .locator('.state-list-item__content')
+    .filter({ has: page.locator(`a:has-text("datamodel-create-cdm_${randomString}")`) })
```
Comment (jerome-ng) [inline tests/e2e/tests/05-datasets/new-schema-i2b2-plugin.spec.ts:51]: using random string for the test so retries will be valid to run as well. also avoiding `xpath=ancestor` selector as it starts looking for the element from the descendant, but the descendant might be gone

File: tests/e2e/tests/05-datasets/new-schema-omop-cdm-plugin-omop53.spec.ts [hunk 10]
```diff
@@ -40,33 +42,36 @@ test(TEST_NAME, async ({ page }) => {
...
   // Get the first (top) entry link
-  const firstEntry = page.locator(`a:has(span:text("datamodel-create-cdm_${randomString}"))`).first()
-  // Find the closest state badge to this entry (adjust the selector as needed)
-  const stateBadge = firstEntry.locator(
-    'xpath=ancestor::div[contains(@class,"state-list-item__content")]//span[contains(@class,"state-badge")]'
-  )
-  await expect(stateBadge).toHaveText(/Completed/, { timeout: 120000 })
+  const firstEntry = page
+    .locator('.state-list-item__content')
+    .filter({ has: page.locator(`a:has-text("datamodel-create-cdm_${randomString}")`) })
```
Comment (jerome-ng) [inline tests/e2e/tests/05-datasets/new-schema-omop-cdm-plugin-omop53.spec.ts:53]: using random string for the test so retries will be valid to run as well

File: tests/e2e/tests/05-datasets/new-schema-omop-cdm-plugin-omop54.spec.ts [hunk 11]
```diff
@@ -39,33 +40,36 @@ test(TEST_NAME, async ({ page }) => {
...
   // Get the first (top) entry link
-  const firstEntry = page.locator(`a:has(span:text("datamodel-create-cdm_${randomString}"))`).first()
-  // Find the closest state badge to this entry (adjust the selector as needed)
-  const stateBadge = firstEntry.locator(
-    'xpath=ancestor::div[contains(@class,"state-list-item__content")]//span[contains(@class,"state-badge")]'
-  )
-  await expect(stateBadge).toHaveText(/Completed/, { timeout: 120000 })
+  const firstEntry = page
+    .locator('.state-list-item__content')
+    .filter({ has: page.locator(`a:has-text("datamodel-create-cdm_${randomString}")`) })
```
Comment (jerome-ng) [inline tests/e2e/tests/05-datasets/new-schema-omop-cdm-plugin-omop54.spec.ts:51]: using random string for the test so retries will be valid to run as well

File: tests/e2e/tests/09-patient-analytics/filtering-barchart.spec.ts [hunk 12]
```diff
@@ -20,7 +20,9 @@ test(TEST_NAME, async ({ page }) => {
   await page.getByRole('button', { name: 'D2E' }).click()
   await expect(page.getByText('2,694 / 2,694')).toBeVisible()
   await expect(page.locator('.loading-animation-component')).not.toBeVisible()
-  await expect(page).toHaveScreenshot({ maxDiffPixels: 100 })
+  // Wait for chart animations to settle
+  await page.waitForTimeout(500)
+  await expect(page).toHaveScreenshot({ maxDiffPixelRatio: 0.1 })
```
Comment (jerome-ng) [inline tests/e2e/tests/09-patient-analytics/filtering-barchart.spec.ts:25]: There seems to be a potential actual bug where the margins of the x1 sometimes is different hence including pixel diff. https://github.com/OHDSI/Data2Evidence/issues/1719

File: tests/e2e/tests/09-patient-analytics/filtering-barchart.spec.ts-snapshots/filtering-barchart-4-linux.png
Comment (jerome-ng) [inline tests/e2e/tests/09-patient-analytics/filtering-barchart.spec.ts-snapshots/filtering-barchart-4-linux.png:1]: Some timing updates have resulted in a slight difference in the Condition concept Name dropdown. see wriggly lines just above Add Filters

File: tests/e2e/tests/09-patient-analytics/filtering-barchart.spec.ts-snapshots/filtering-barchart-5-actual.png
Comment (jerome-ng) [inline tests/e2e/tests/09-patient-analytics/filtering-barchart.spec.ts-snapshots/filtering-barchart-5-actual.png:1]: this file is unused

File: tests/e2e/tests/09-patient-analytics/patient-group_comparison.spec.ts [hunk 13]
```diff
@@ -106,12 +106,18 @@ test('pa-compare-cohorts', async ({ page }) => {
   // await page.locator('.footer > div:nth-child(5)').first().click()
   // await page.getByRole('button', { name: 'Delete' }).click()
 
-  await page.getByTitle('Delete Saved Filter').first().click()
-  await page.getByRole('button', { name: 'Delete' }).click()
-  await page.waitForTimeout(25000)
-  await page.getByTitle('Delete Saved Filter').first().click()
-  await page.getByRole('button', { name: 'Delete' }).click()
-  await page.waitForTimeout(25000)
+  // Delete all saved cohorts until none remain
```
Comment (jerome-ng) [inline tests/e2e/tests/09-patient-analytics/patient-group_comparison.spec.ts:109]: Some test runs might have created more cohorts, and the previous logic assumed 2 only

File: tests/e2e/tests/09-patient-analytics/patient-list.spec.ts [hunk 14]
```diff
@@ -52,22 +54,12 @@ test(TEST_NAME, async ({ page }) => {
         .first()
         .click()
       await page.getByRole('button', { name: 'Create' }).click()
+      // Wait for Create button to change to Update (confirms concept set was created)
+      await expect(page.getByRole('button', { name: 'Update' })).toBeVisible()
       await page.getByRole('button', { name: 'Close' }).click()
       await expect(page.locator('.loading-animation-component')).not.toBeVisible()
-      // Click modal backdrop to dismiss it
-      await page.locator('.modal-wrapper').click()
```
Comment (jerome-ng) [inline tests/e2e/tests/09-patient-analytics/patient-list.spec.ts:59]: This section is not needed and caused errors sometimes. The concept set is already selected automatically when the terminology modal is closed so there is not need to search for it and add again

File: tests/e2e/tests/12-concepts/concept-sets.spec.ts-snapshots/concept-sets-2-linux.png
Comment (jerome-ng) [inline tests/e2e/tests/12-concepts/concept-sets.spec.ts-snapshots/concept-sets-2-linux.png:1]: Moved the screenshot check 1 step further so dropdown disappears reliably

File: tests/e2e/tests/17-configurations/CDM-creation.spec.ts [hunk 15]
```diff
@@ -84,292 +96,310 @@ test(TEST_NAME, async ({ page }) => {
...
+    await page.screenshot({ path: `test-results/retry-${testInfo.retry}/debug-03-after-yes-click.png` })
+    await page.getByRole('radio', { name: 'ADVANCED', exact: true }).click()
+    await page.screenshot({ path: `test-results/retry-${testInfo.retry}/debug-04-advanced-selected.png` })
+    // Get reference to the visible validation error before filling the input
+    const validationError = page.getByText('Please provide either a data source or a measure expression.').first()
+    await expect(validationError).toBeVisible()
+    const dataSourceInput = page.locator('[id="__xmlview11--AttributeDataSource-inner"]')
+    await dataSourceInput.click()
+    await dataSourceInput.clear()
+    await dataSourceInput.pressSequentially('CAST (@COND."CONDITION_CONCEPT_ID" AS VARCHAR)')
```
Comment (jerome-ng) [inline tests/e2e/tests/17-configurations/CDM-creation.spec.ts:362]: Notable change in this file is change from `.fill()` to `.pressSequentially()`. the CDM config ui does not seem to trigger the backend validation after blur when fill is used when `fill` is used.

File: tests/e2e/tests/17-configurations/CDM-creation.spec.ts-snapshots/CDM-configuration-creation-1-linux.png
Comment (jerome-ng) [inline tests/e2e/tests/17-configurations/CDM-creation.spec.ts-snapshots/CDM-configuration-creation-1-linux.png:1]: When the validate button is pressed, the config should be valid. the yellow line on the left of Condition Occurrence (behind the pop up) is not supposed to be there. This is present because the validation was not completed due to `.fill()` not triggering some validation checks.

File: tests/e2e/tests/fixtures.ts [hunk 16]
```diff
@@ -0,0 +1,95 @@
+import { test as base, Page, BrowserContext } from '@playwright/test'
```
Comment (jerome-ng) [inline tests/e2e/tests/fixtures.ts:1]: Storing the console logs in each retry folder in the test results

File: ui/Dockerfile.build (hunk 2 above)
Comment (jerome-ng) [reply ui/Dockerfile.build:1]: The actual UI build to resources is done by running a container of this image, which makes use of the nx caching mechanism. So if u had built previously locally, subsequent builds will be much faster when using `e2e.sh`

File: ui/package.json [hunk 17]
```diff
@@ -9,6 +9,7 @@
   "license": "Apache-2.0",
   "scripts": {
     "build-all": "bunx nx run-many --targets=build --projects=@portal/components,@portal/plugin && bunx nx run-many --targets=build,build-mri --exclude @portal/components,@portal/plugin && bun build-ui5 && bun build-starboard && bun build-gateway",
+    "build-docker": "docker build -f Dockerfile.build -t d2e-ui-builder . && docker run --rm -v \"$(pwd):/app\" d2e-ui-builder",
```
Comment (jerome-ng) [inline ui/package.json:12]: Used in `e2e.sh` for building ui resources. can potentially be used as standard build method for reproducibility.

File: .github/workflows/d2e-demosetup-dev.yml [hunk 18]
```diff
@@ -202,27 +202,57 @@ jobs:
           ENV_TYPE=remote CADDY__CONFIG=./deploy/caddy-config node ./scripts/dist/cli.js -e -v ${{ env.VERSION }} -d ./functions stop
           ENV_TYPE=remote CADDY__CONFIG=./deploy/caddy-config node ./scripts/dist/cli.js -e -v ${{ env.VERSION }} -d ./functions start
 
-      - name: Wait for services to be ready to avoid mounting race condition
+      - name: Wait for d2e-ui plugin to be installed
```
Comment (jerome-ng) [inline .github/workflows/d2e-demosetup-dev.yml:211]: Prevents race condition where network might be very slow, and only pull the package after the UI copy happens

File: .github/workflows/d2e-demosetup-dev.yml [hunk 19]
```diff
@@ -202,27 +202,57 @@ jobs:
...
+        run: |
+          curl -k -s -o /dev/null -w "%{http_code}" https://localhost:443/d2e/portal || echo "App not reachable"
+          curl -k -I https://localhost:443/d2e/portal || true
 
       - name: e2e tests
-        # continue-on-error: true
         run: |
           cd ./tests/e2e
-          npm test
+          docker run --rm \
```
Comment (jerome-ng) [inline .github/workflows/d2e-demosetup-dev.yml:254]: Run playwright in docker container so same environment in local and github actions

**Review by hengxian-jiang — APPROVED** [review]

**Review by maggie-li-yd — APPROVED** [review]
Look forward to being able to run e2e tests locally!

**Review by satish-a0 — APPROVED** [review]

**Review by p-hoffmann — APPROVED** [review]
