### PR TITLE
[BaseTagInput] Improve handling of option selection and dropdown beha…

### LINKED ISSUE #1772: Empty results panel remains visible after adding condition in filter card
After selecting a condition source concept in the Conditions (ICD10CM) filter, an empty white results panel remains visible below the filter input. This panel does not contain any content and persists even after valid conditions have been added.

This creates visual clutter and may confuse users, as the empty panel appears to suggest missing or failed results.

Steps to Reproduce
	1.	Navigate to the Conditions filter
	2.	In Condition Source concept code, search for and select a valid concept (e.g. Malignant neoplasm of breast), hit enter
	3.	Observe the UI after the concept is added to the filter

Image

### PR DESCRIPTION
**Pull request by jerome-ng**
…vior

### Merge Checklist

Please cross check this list if additions / modifications needs to be done on top of your core changes and tick them off. Reviewer can as well glance through and help the developer if something is missed out.

- [ ] Automated Tests (Jasmine integration tests, Unit tests, and/or Performance tests)
- [ ] Updated Manual tests / Demo Config
- [ ] Documentation (Application guide, Admin guide, Markdown, Readme and/or Wiki)
- [ ] Verified that local development environment is working with latest changes (integrated with latest `develop` branch)
- [ ] following best practices in [code review doc](../code_review.md)

### CODE REVIEW

File: ui/apps/vue-mri-ui-lib/src/lib/ui/BaseTagInput.vue [hunk 1]
```diff
@@ -260,6 +261,24 @@ export default {
       // For other types, use normal behavior
       this.openControl()
     },
+    handleSelectOption() {
+      if (this.componentType !== 'conceptSet') {
+        // Skip the empty search triggered by clear-on-select to retain previous results
+        this.skipNextEmptySearch = true
```
Comment (jerome-ng) [inline ui/apps/vue-mri-ui-lib/src/lib/ui/BaseTagInput.vue:267]: In the past we used to show the previous search results after selecting 1 as the previous search probably included other results of interest. Recently we added a search for empty '' search, which changed it to do an empty search after selecting from the dropdown. This flag helps get the old behaviour back

File: ui/apps/vue-mri-ui-lib/src/lib/ui/BaseTagInput.vue [hunk 2]
```diff
@@ -260,6 +261,24 @@ export default {
...
+      if (!(this.componentType === 'conceptSet' && this.maxSelections === 1)) {
+        this.openControl()
+      }
+      this.$nextTick(() => {
+        if (this.allOptionsSelected) {
+          // Close dropdown if all options are now selected (nothing left to show)
+          this.$refs.multiselect?.deactivate()
+        } else {
+          // Recalculate dropdown height for remaining visible options
+          this.adjustDropdownHeight()
```
Comment (jerome-ng) [inline ui/apps/vue-mri-ui-lib/src/lib/ui/BaseTagInput.vue:278]: dropdown was not resizing when the leftover options was less than the original options, so there is extra whitespace at the bottom. This triggers the dropdown size when the option count changes

File: ui/apps/vue-mri-ui-lib/src/lib/ui/BaseTagInput.vue [hunk 3]
```diff
@@ -456,7 +486,7 @@ export default {
           if (content) {
             // Calculate expected height based on filteredList (each item is 40px)
             const expectedHeight = (this.filteredList.length - this.selectedValues.length) * 40
-            const minHeight = Math.min(expectedHeight, 200)
+            const minHeight = Math.max(0, Math.min(expectedHeight, 200))
```
Comment (jerome-ng) [inline ui/apps/vue-mri-ui-lib/src/lib/ui/BaseTagInput.vue:489]: The minHeight could become negative value eg `-200px` which the browser ignores, which leaves whatever height was there before. Instead we want the min height to be 0.

**Review by khairul-syazwan — APPROVED** [review]
